### ISSUE TITLE
Example device code broken by upgrade in TypeScript version

### ISSUE THREAD

**Issue by m-lieshout-adi** [adinstruments/LightningDeviceSDK#24]
When Lightning was upgraded to 1.4 the version of TypeScript it was compiled against was upgraded. All plugins are compiled against this version, and the version bump for TypeScript created a breaking change - try catch clauses now implicitly have their error object type as unknown instead of any.

The example plugins need to be updated to compile against this newer version of TypeScript to stay compatible with the latest versions of Lightning. This is as simple as adding explicit `any` types to the catch clauses.

**Comment by ajackson-adi** [comment]
Fixed on Master
